### PR TITLE
Don't iterate if object is null

### LINKED ISSUE #766: getApprovalLink is using getLink which is a foreach
### Required Information

- PHP Version: 7
- PayPal-PHP-SDK Version: latest
- Debug ID(s):

### Issue Description

In the src folder: api/payment.php line: 402 you are using the following:

    public function getApprovalLink()
    {
        return $this->getLink(PayPalConstants::APPROVAL_URL);
    }

In the common/paypalresource.php the method for that call is:

    public function getLink($rel)
    {
		
        foreach ($this->links as $link) {
            if ($link->getRel() == $rel) {
                return $link->getHref();
            }
        }
        return null;
    }

Which causes an error because it's trying to loop through a constant. The error for this is: 

> ErrorException in PayPalResourceModel.php line 46:
> Invalid argument supplied for foreach()

Full stack of the error if that's any help:

> in PayPalResourceModel.php line 46
> at HandleExceptions->handleError('2', 'Invalid argument supplied for foreach()', 'C:\xampp\htdocs\jobs\vendor\paypal\rest-api-sdk-php\lib\PayPal\Common\PayPalResourceModel.php', '46', array('rel' => 'approval_url')) in PayPalResourceModel.php line 46
> at PayPalResourceModel->getLink('approval_url') in Payment.php line 404
> at Payment->getApprovalLink() in PaymentController.php line 137
> at PaymentController->getPayment('1', 'job')

### PR DESCRIPTION
**Pull request by jaypatel512**
- Fixes #766.

### CODE REVIEW

File: lib/PayPal/Common/PayPalResourceModel.php [hunk 1]
```diff
@@ -41,9 +41,11 @@ public function getLinks()
 
     public function getLink($rel)
     {
-        foreach ($this->links as $link) {
-            if ($link->getRel() == $rel) {
-                return $link->getHref();
+        if ($this->links) {
```
Comment (bluk) [inline lib/PayPal/Common/PayPalResourceModel.php]: Instead of just testing if this is a non-falsy value, can we add a test like `if (is_array($this->links))`?

Comment (jaypatel512) [inline lib/PayPal/Common/PayPalResourceModel.php]: Completed the changes.
